### ISSUE TITLE
Max homes message is incorrect

### ISSUE THREAD

**Issue by phofers** [WiIIiam278/HuskHomes#627] opened 2024-05-08 22:34 UTC
If you already have the maximum number of homes allowed, creating a new one will display an incorrect message (at least in my case). I had 5 homes (which I believe is the server's limit) already created, and when I tried to make a 6th using `/sethome Name` it sent me the message: `Error: You can only set a maximum of 50 homes!`.
I'm fairly sure it should have instead said I can only make a maximum of 5 homes.

This was on a Fabric 1.20.4 server.

**Comment by WiIIiam278** [comment] 2024-05-08 23:50
Duplicate of https://github.com/WiIIiam278/HuskHomes/issues/614

FYI: Please use the Bug report system on the Dogcraft site to report bugs, this issue tracker is for issues facing server admins :)

**Closed by WiIIiam278** 2024-05-08 23:50 UTC

**Comment by phofers** [comment] 2024-05-08 23:51
> Duplicate of #614
> 
> FYI: Please use the Bug report system on the Dogcraft site to report bugs, this issue tracker is for issues facing server admins :)

Woops, sorry about that. Also I somehow didn't realize that was a duplicate. Sorry!
