### ISSUE TITLE
When /home all XP levels is lost

### ISSUE THREAD

**Issue by resiresi1** [WiIIiam278/HuskHomes#461] opened 2023-07-14 20:12 UTC
When I /home from a different dimension that my home is in, aka
/home from the nether and my homes in the overworld

all my XP levels are lost.

using fabric 1.20.1 v4.4.1

**Comment by WiIIiam278** [comment] 2023-07-15 12:13
Duplicate of #457

**Closed by WiIIiam278** 2023-07-15 12:13 UTC

**Comment by WiIIiam278** [comment] 2023-07-15 13:59
@resiresi1 Fixed in 4.4.2
