### ISSUE TITLE
back protection

### ISSUE THREAD

**Issue by zwqwei** [WiIIiam278/HuskHomes#589] opened 2024-03-03 13:52 UTC
Does /back have a protection function?

**Comment by WiIIiam278** [comment] 2024-03-03 14:08
Please clarify what you mean by protection? :)

**Comment by zwqwei** [comment] 2024-03-03 15:49
When I die in the lava /back will be passed back to the lava 0.0

**Comment by WiIIiam278** [comment] 2024-03-03 15:51
Sounds like you're looking for teleport safety, which isn't a feature at the moment.

Duplicate of #36

**Closed by WiIIiam278** 2024-03-03 15:51 UTC
Labels: type: question

**Comment by zwqwei** [comment] 2024-03-03 15:53
So can you add this function? I've been troubled for a long time :(
