### ISSUE TITLE
Unable to transmit properly in Folia 1.20.6

### ISSUE THREAD

**Issue by xiantiao233** [WiIIiam278/HuskHomes#660] opened 2024-07-15 12:14 UTC
velocity-3.3.0-SNAPSHOT-406
Lobby - paper-1.20.6-148
Main   - Folia-1.20.6-build5

There are no errors in the console

Only the transmission does not work, everything else works normally
For example, during the second reading before transmission, the 'tpa' prompt indicates that it can be transmitted to another server
'spawn' can read in seconds

**Comment by WiIIiam278** [comment] 2024-07-15 13:04
Duplicate of #633

**Closed by WiIIiam278** 2024-07-15 13:04 UTC
