### ISSUE TITLE
player death error

### ISSUE THREAD

**Issue by jhqwqmc** [WiIIiam278/HuskHomes#472] opened 2023-07-25 08:01 UTC
When the player dies, the message returned by death cannot be prompted, and the console reports an error. The version is 1.19.3, the Java version is 18, and the purpur core is used.

The following is the content of the error:
[15:55:41 ERROR]: Could not pass event PlayerRespawnEvent to HuskHomes v4.4.5
java.lang.NoSuchMethodError: 'org.bukkit.event.player.PlayerRespawnEvent$RespawnReason org.bukkit.event.player.PlayerRespawnEvent.getRespawnReason()'
        at net.william278.huskhomes.listener.BukkitEventListener.onPlayerRespawn(BukkitEventListener.java:63) ~[[H][传送]HuskHomes-Plugin-4.4.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1418.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1913]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:873) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:776) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:771) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleClientCommand(ServerGamePacketListenerImpl.java:3001) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.handle(ServerboundClientCommandPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.a(ServerboundClientCommandPacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by WiIIiam278** [comment] 2023-07-25 08:18
Duplicate of #467 
Purpur bug with that version; update to 1.20.1

**Closed by WiIIiam278** 2023-07-25 08:18 UTC
