### ISSUE TITLE
Player home lost

### ISSUE THREAD

**Issue by CodeZhangBorui** [WiIIiam278/HuskHomes#696] opened 2024-10-03 06:56 UTC
**Reopen issue of #658**

Problem still occurs here, with plugin [fakeplayer](https://github.com/tanyaofei/minecraft-fakeplayer/).

**Version:** PaperMC 1.20.1 & HuskHomes-Paper-4.7.1-ab7237f.

```
[12:31:29 INFO]: LSamoyedy lost connection: Disconnected
[12:31:29 INFO]: - LSamoyedy left the server
[12:41:05 INFO]: LSamoyedy_Bot_1 lost connection: [fakeplayer] Creator offline
[12:41:05 INFO]: - LSamoyedy_Bot_1 left the server
[12:41:05 INFO]: LSamoyedy_Bot_2 lost connection: [fakeplayer] Creator offline
[12:41:05 INFO]: - LSamoyedy_Bot_2 left the server
[12:41:05 INFO]: [fakeplayer] LSamoyedy is offline more than 12000 ticks, removing 2 fake players
[12:41:05 ERROR]: [HuskHomes] Failed to set the offline position of LSamoyedy_Bot_2
org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (cannot commit transaction - SQL statements in progress)
        at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.throwex(DB.java:1150) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.ensureAutocommit(DB.java:1255) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.lambda$ensureAutoCommit$2(DB.java:1226) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.SafeStmtPtr.safeRunConsume(SafeStmtPtr.java:142) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.lambda$ensureAutoCommit$3(DB.java:1225) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.SafeStmtPtr.safeRunConsume(SafeStmtPtr.java:142) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.ensureAutoCommit(DB.java:1223) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.execute(DB.java:977) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.executeUpdate(DB.java:1054) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:119) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:118) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:100) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at net.william278.huskhomes.database.SqLiteDatabase.updatePosition(SqLiteDatabase.java:178) ~[HuskHomes-Paper-4.7.1-ab7237f.jar:?]
        at net.william278.huskhomes.database.SqLiteDatabase.setOfflinePosition(SqLiteDatabase.java:894) ~[HuskHomes-Paper-4.7.1-ab7237f.jar:?]
        at net.william278.huskhomes.listener.EventListener.lambda$handlePlayerLeave$7(EventListener.java:107) ~[HuskHomes-Paper-4.7.1-ab7237f.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by WiIIiam278** [comment] 2024-10-05 10:57
Duplicate of #688, but will copy your report over there. Thanks.

**Closed by WiIIiam278** 2024-10-05 10:57 UTC
