### ISSUE TITLE
Using home on 1.20.6 or 1.21 may cause server crashes

### ISSUE THREAD

**Issue by buildin1** [WiIIiam278/HuskHomes#669] opened 2024-08-06 09:14 UTC
[统计.txt](https://github.com/user-attachments/files/16508140/default.txt)
This is all the crash reports I have collected, and it can be seen that every time I use Home, it causes the server to crash

Folia1.20.6/1.21

**Comment by WiIIiam278** [comment] 2024-08-06 10:28
Duplicate of #633.

Folia is still experimental.

**Closed by WiIIiam278** 2024-08-06 10:28 UTC

**Comment by buildin1** [comment] 2024-08-06 11:11
But this error keeps causing the server to crash, is there any solution
