### ISSUE TITLE
Failed to insert a player into the database

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes#493] opened 2023-09-09 06:57 UTC
These errors occur when a new player joins, and a redundant position is generated in the database. This position is not referenced in any other data.

I can't find the reason for this error... (It started happening before I submitted the PR)

![image](https://github.com/WiIIiam278/HuskHomes/assets/59365724/d6b9556f-d84c-4388-8f7a-3463e572c839)
![image](https://github.com/WiIIiam278/HuskHomes/assets/59365724/d405257c-bc3f-44d8-ab69-b34e3d4dfaa2)

```
[14:37:14 ERROR]: [HuskHomes] Failed to insert a player into the database
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: huskhomes_users.uuid)
        at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.execute(DB.java:985) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.executeUpdate(DB.java:1054) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:119) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:118) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:100) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at net.william278.huskhomes.database.SqLiteDatabase.lambda$ensureUser$1(SqLiteDatabase.java:269) ~[HuskHomes-Plugin-4.5-f7c0917-indev.jar:?]
        at java.util.Optional.ifPresentOrElse(Optional.java:198) ~[?:?]
        at net.william278.huskhomes.database.SqLiteDatabase.ensureUser(SqLiteDatabase.java:241) ~[HuskHomes-Plugin-4.5-f7c0917-indev.jar:?]
        at net.william278.huskhomes.listener.EventListener.lambda$handlePlayerJoin$3(EventListener.java:60) ~[HuskHomes-Plugin-4.5-f7c0917-indev.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[divinemc-1.20.1.jar:git-DivineMC-"e1a2651"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[divinemc-1.20.1.jar:git-DivineMC-"e1a2651"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[divinemc-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by WiIIiam278** [comment] 2023-09-10 13:30
Can't seem to reproduce this :/

**Comment by ApliNi** [comment] 2023-09-10 13:39
This is weird, but it's reproducible reliably on my server, and I'm using the default configuration.
I retested with the latest build here.

Is there any additional information I should provide to help troubleshoot the issue?

**Comment by ApliNi** [comment] 2023-09-10 13:43
complete log:
```
OpenJDK 64-Bit Server VM warning: JVM cannot use large page memory because it does not have enough privilege to lock pages in memory.
OpenJDK 64-Bit Server VM warning: UseAVX=3 is not supported on this CPU, setting it to UseAVX=2
WARNING: Using incubator modules: jdk.incubator.vector
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.8.1+1) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[21:41:56 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:41:58 INFO]: Loaded 7 recipes
[21:41:58 INFO]: Starting minecraft server version 1.20.1
[21:41:58 INFO]: Loading properties
[21:41:58 INFO]: This server is running DivineMC version git-DivineMC-"e1a2651" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: e1a2651 on ver/1.20.1)
[21:41:58 INFO]: Server Ping Player Sample Count: 0
[21:41:58 INFO]: Using 4 threads for Netty based IO
[21:41:58 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[21:41:59 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (int)
[21:41:59 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (float)
[21:41:59 INFO]: [Pufferfish] SIMD operations detected as functional. Will replace some operations with faster versions.
[21:41:59 INFO]: Default game type: SURVIVAL
[21:41:59 INFO]: Generating keypair
[21:42:00 INFO]: Starting Minecraft server on *:25565
[21:42:00 INFO]: Using default channel type
[21:42:00 INFO]: Paper: Using Java compression from Velocity.
[21:42:00 INFO]: Paper: Using Java cipher from Velocity.
[21:42:00 INFO]: [ViaVersion] Loading server plugin ViaVersion v4.7.0
[21:42:00 INFO]: [ViaVersion] ViaVersion 4.7.0 is now loaded. Registering protocol transformers and injecting...
[21:42:01 INFO]: [ViaVersion] Loading block connection mappings ...
[21:42:01 INFO]: [ViaBackwards] Loading translations...
[21:42:01 INFO]: [ViaBackwards] Registering protocols...
[21:42:01 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[21:42:01 INFO]: [HuskHomes] Loading server plugin HuskHomes v4.5-f8218d7
[21:42:01 INFO]: [ViaBackwards] Loading server plugin ViaBackwards v4.7.0
[21:42:01 INFO]: [HuskHomesGUI] Loading server plugin HuskHomesGUI v2.3-69af32a-indev
[21:42:01 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[21:42:01 WARN]: The server will make no attempt to authenticate usernames. Beware.
[21:42:01 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[21:42:01 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[21:42:01 INFO]: Preparing level "world"
[21:42:02 INFO]: [ViaVersion] Enabling ViaVersion v4.7.0
[21:42:02 INFO]: [ViaVersion] ViaVersion detected server version: 1.20 (763)
[21:42:02 INFO]: [HuskHomes] Enabling HuskHomes v4.5-f8218d7
[21:42:02 INFO]: [HuskHomes] Initializing plugin config & locale files...
[21:42:02 INFO]: [HuskHomes] Successfully initialized plugin config & locale files
[21:42:02 INFO]: [HuskHomes] Initializing SQLite database connection...
[21:42:02 INFO]: [HuskHomes] Created the SQLite database file
[21:42:03 INFO]: [HuskHomes] Successfully initialized SQLite database connection
[21:42:03 INFO]: [HuskHomes] Initializing hooks...
[21:42:03 INFO]: [HuskHomes] Successfully initialized hooks
[21:42:03 INFO]: [HuskHomes] Initializing events...
[21:42:03 INFO]: [HuskHomes] Successfully initialized events
[21:42:03 INFO]: [HuskHomes] Initializing commands...
[21:42:03 INFO]: [HuskHomes] Successfully initialized commands
[21:42:03 INFO]: [HuskHomes] Initializing API...
[21:42:03 INFO]: [HuskHomes] Successfully initialized API
[21:42:03 INFO]: [HuskHomes] Initializing metrics...
[21:42:03 INFO]: [HuskHomes] Successfully initialized metrics
[21:42:03 INFO]: [ViaBackwards] Enabling ViaBackwards v4.7.0
[21:42:03 INFO]: [HuskHomesGUI] Enabling HuskHomesGUI v2.3-69af32a-indev
[21:42:03 INFO]: [HuskHomesGUI] Successfully enabled HuskHomes v2.3-69af32a-indev
[21:42:03 INFO]: JMX monitoring enabled
[21:42:03 INFO]: Running delayed init tasks
[21:42:03 INFO]: Done (5.088s)! For help, type "help"
[21:42:03 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[21:42:03 WARN]: [ViaVersion] Could not check for updates, check your connection.
[21:42:09 INFO]: UUID of player ApliNi is a1d1c2cd-42e5-394d-961a-8ee6680df4f8
[21:42:09 INFO]: ApliNi joined the game
[21:42:09 INFO]: ApliNi[/[0:0:0:0:0:0:0:1]:6704] logged in with entity id 1 at ([world]5.5, 71.0, -2.5)
[21:42:09 ERROR]: [HuskHomes] Failed to insert a player into the database
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: huskhomes_users.uuid)
        at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.execute(DB.java:985) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.executeUpdate(DB.java:1054) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:119) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:118) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:100) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at net.william278.huskhomes.database.SqLiteDatabase.lambda$ensureUser$1(SqLiteDatabase.java:269) ~[HuskHomes-Plugin-4.5-f8218d7.jar:?]
        at java.util.Optional.ifPresentOrElse(Optional.java:198) ~[?:?]
        at net.william278.huskhomes.database.SqLiteDatabase.ensureUser(SqLiteDatabase.java:241) ~[HuskHomes-Plugin-4.5-f8218d7.jar:?]
        at net.william278.huskhomes.listener.EventListener.lambda$handlePlayerJoin$3(EventListener.java:60) ~[HuskHomes-Plugin-4.5-f8218d7.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[divinemc-1.20.1.jar:git-DivineMC-"e1a2651"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[divinemc-1.20.1.jar:git-DivineMC-"e1a2651"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[divinemc-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:42:11 INFO]: ApliNi lost connection: Disconnected
[21:42:11 INFO]: ApliNi left the game
```

---

SQLite database file:
[HuskHomesData.zip](https://github.com/WiIIiam278/HuskHomes/files/12568300/HuskHomesData.zip)

**Comment by WiIIiam278** [comment] 2023-09-10 14:11
The error implies that the `getUserData` method is returning an empty optional and can't find your existing user entry when trying to ensure your user.

Could you try
-reproducing on Paper 1.20.1 (not the fork you are running)?
-reproducing on a single-server instance running online mode

**Comment by ApliNi** [comment] 2023-09-10 14:19
Tested, it also happens on paper server using default configuration:

log:
```
OpenJDK 64-Bit Server VM warning: JVM cannot use large page memory because it does not have enough privilege to lock pages in memory.
OpenJDK 64-Bit Server VM warning: UseAVX=3 is not supported on this CPU, setting it to UseAVX=2
WARNING: Using incubator modules: jdk.incubator.vector
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.8.1+1) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[22:17:01 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:17:01 INFO]: Found new data pack file/bukkit, loading it automatically
[22:17:03 INFO]: Loaded 7 recipes
[22:17:03 INFO]: Starting minecraft server version 1.20.1
[22:17:03 INFO]: Loading properties
[22:17:03 INFO]: This server is running Paper version git-Paper-172 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 72e87ab)
[22:17:03 INFO]: Server Ping Player Sample Count: 12
[22:17:03 INFO]: Using 4 threads for Netty based IO
[22:17:04 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[22:17:04 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[22:17:04 INFO]: Default game type: SURVIVAL
[22:17:04 INFO]: Generating keypair
[22:17:04 INFO]: Starting Minecraft server on *:25565
[22:17:04 INFO]: Using default channel type
[22:17:04 INFO]: Paper: Using Java compression from Velocity.
[22:17:04 INFO]: Paper: Using Java cipher from Velocity.
[22:17:05 INFO]: [ViaVersion] Loading server plugin ViaVersion v4.7.0
[22:17:05 INFO]: [ViaVersion] ViaVersion 4.7.0 is now loaded. Registering protocol transformers and injecting...
[22:17:05 INFO]: [ViaVersion] Loading block connection mappings ...
[22:17:05 INFO]: [ViaBackwards] Loading translations...
[22:17:05 INFO]: [ViaBackwards] Registering protocols...
[22:17:05 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[22:17:06 INFO]: [HuskHomes] Loading server plugin HuskHomes v4.5-f8218d7
[22:17:06 INFO]: [ViaBackwards] Loading server plugin ViaBackwards v4.7.0
[22:17:06 INFO]: [HuskHomesGUI] Loading server plugin HuskHomesGUI v2.3-69af32a-indev
[22:17:06 INFO]: Preparing level "world"
[22:17:12 INFO]: Preparing start region for dimension minecraft:overworld
[22:17:12 INFO]: Time elapsed: 147 ms
[22:17:12 INFO]: Preparing start region for dimension minecraft:the_nether
[22:17:12 INFO]: Time elapsed: 158 ms
[22:17:12 INFO]: Preparing start region for dimension minecraft:the_end
[22:17:12 INFO]: Time elapsed: 112 ms
[22:17:12 INFO]: [ViaVersion] Enabling ViaVersion v4.7.0
[22:17:12 INFO]: [ViaVersion] ViaVersion detected server version: 1.20 (763)
[22:17:12 INFO]: [HuskHomes] Enabling HuskHomes v4.5-f8218d7
[22:17:13 INFO]: [HuskHomes] Initializing plugin config & locale files...
[22:17:13 INFO]: [HuskHomes] Successfully initialized plugin config & locale files
[22:17:13 INFO]: [HuskHomes] Initializing SQLite database connection...
[22:17:13 INFO]: [HuskHomes] Created the SQLite database file
[22:17:13 INFO]: [HuskHomes] Successfully initialized SQLite database connection
[22:17:13 INFO]: [HuskHomes] Initializing hooks...
[22:17:13 INFO]: [HuskHomes] Successfully initialized hooks
[22:17:13 INFO]: [HuskHomes] Initializing events...
[22:17:13 INFO]: [HuskHomes] Successfully initialized events
[22:17:13 INFO]: [HuskHomes] Initializing commands...
[22:17:13 INFO]: [HuskHomes] Successfully initialized commands
[22:17:13 INFO]: [HuskHomes] Initializing API...
[22:17:13 INFO]: [HuskHomes] Successfully initialized API
[22:17:13 INFO]: [HuskHomes] Initializing metrics...
[22:17:13 INFO]: [HuskHomes] Successfully initialized metrics
[22:17:13 INFO]: [ViaBackwards] Enabling ViaBackwards v4.7.0
[22:17:13 INFO]: [HuskHomesGUI] Enabling HuskHomesGUI v2.3-69af32a-indev
[22:17:13 INFO]: [HuskHomesGUI] Successfully enabled HuskHomes v2.3-69af32a-indev
[22:17:13 INFO]: Running delayed init tasks
[22:17:13 INFO]: Done (10.159s)! For help, type "help"
[22:17:13 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[22:17:13 INFO]: Timings Reset
[22:17:13 WARN]: [ViaVersion] Could not check for updates, check your connection.
[22:17:29 INFO]: UUID of player ApliNi is c5c3a31f-2e13-407c-9591-42401b02d14d
[22:17:29 INFO]: ApliNi joined the game
[22:17:29 INFO]: ApliNi[/[0:0:0:0:0:0:0:1]:52231] logged in with entity id 58 at ([world]2.5, 72.0, 23.5)
[22:17:29 ERROR]: [HuskHomes] Failed to insert a player into the database
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: huskhomes_users.uuid)
        at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.execute(DB.java:985) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.executeUpdate(DB.java:1054) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:119) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:118) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:100) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at net.william278.huskhomes.database.SqLiteDatabase.lambda$ensureUser$1(SqLiteDatabase.java:269) ~[HuskHomes-Plugin-4.5-f8218d7.jar:?]
        at java.util.Optional.ifPresentOrElse(Optional.java:198) ~[?:?]
        at net.william278.huskhomes.database.SqLiteDatabase.ensureUser(SqLiteDatabase.java:241) ~[HuskHomes-Plugin-4.5-f8218d7.jar:?]
        at net.william278.huskhomes.listener.EventListener.lambda$handlePlayerJoin$3(EventListener.java:60) ~[HuskHomes-Plugin-4.5-f8218d7.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-172]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:17:39 INFO]: ApliNi lost connection: Disconnected
[22:17:39 INFO]: ApliNi left the game
```

SQLite:
[HuskHomesData.zip](https://github.com/WiIIiam278/HuskHomes/files/12568389/HuskHomesData.zip)

**Comment by ApliNi** [comment] 2023-09-10 14:22
Meanwhile I tested version 4.4.5, it only creates a position and there are no errors in the console:
[HuskHomesData.zip](https://github.com/WiIIiam278/HuskHomes/files/12568398/HuskHomesData.zip)

**Comment by ApliNi** [comment] 2023-09-10 14:30
Another error occurred on the production server, but I couldn't reproduce it in testing.
```
[17:28:33 ERROR]: [HuskHomes] Failed to set the offline position of ikunuu
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_FOREIGNKEY] A foreign key constraint failed (FOREIGN KEY constraint failed)
        at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.execute(DB.java:985) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.executeUpdate(DB.java:1054) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:119) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:118) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:100) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at net.william278.huskhomes.database.SqLiteDatabase.setOfflinePosition(SqLiteDatabase.java:843) ~[HuskHomes-Plugin-4.5-091430b.jar:?]
        at net.william278.huskhomes.listener.EventListener.lambda$handlePlayerLeave$7(EventListener.java:103) ~[HuskHomes-Plugin-4.5-091430b.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[divinemc-1.20.1.jar:git-DivineMC-"aade6ab"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[divinemc-1.20.1.jar:git-DivineMC-"aade6ab"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[divinemc-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[17:28:33 ERROR]: [HuskHomes] Failed to set the offline position of ikunuu
java.sql.SQLException: ResultSet already requested
        at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:152) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeQuery$1(JDBC3PreparedStatement.java:94) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:82) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3DatabaseMetaData.getGeneratedKeys(JDBC3DatabaseMetaData.java:1936) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3Statement.getGeneratedKeys(JDBC3Statement.java:356) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at net.william278.huskhomes.database.SqLiteDatabase.setPosition(SqLiteDatabase.java:146) ~[HuskHomes-Plugin-4.5-091430b.jar:?]
        at net.william278.huskhomes.database.SqLiteDatabase.setOfflinePosition(SqLiteDatabase.java:841) ~[HuskHomes-Plugin-4.5-091430b.jar:?]
        at net.william278.huskhomes.listener.EventListener.lambda$handlePlayerLeave$7(EventListener.java:103) ~[HuskHomes-Plugin-4.5-091430b.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[divinemc-1.20.1.jar:git-DivineMC-"aade6ab"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[divinemc-1.20.1.jar:git-DivineMC-"aade6ab"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[divinemc-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by WiIIiam278** [comment] 2023-09-10 14:36
can you repro with a fresh DB?

**Comment by ApliNi** [comment] 2023-09-10 14:39
I deleted the database file every time I tested

**Comment by WiIIiam278** [comment] 2023-09-10 14:56
alright I can reproduce on Paper weirdly enough. I have one idea why this may be.

**Comment by WiIIiam278** [comment] 2023-09-10 15:01
Fixed by https://github.com/WiIIiam278/HuskHomes/commit/e579b2b05e63144a0ae71595ea1266a3c50a9830

The reason I couldn't reproduce this in Fabric was because it was indeed a platform specific issue. I changed listener registration logic awhile back to fix a Paper-side bug where respawn handling wasn't being done correctly and this meant listeners were accidentally being done twice.

I've tested and can no longer reproduce -- please let me know if it's the same for you.

**Closed** 2023-09-10 15:05 UTC
Labels: type: bug, platform: spigot
